# Generated by Django 4.0.2 on 2022-02-05 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_produto_foto_produto_statu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='statu',
            new_name='status',
        ),
    ]
